template-file-path: todo-app-ecs2.yaml
parameters:
  PrivateSubnet1CIDR: 10.0.3.0/24
  PublicSubnet2CIDR: 10.0.2.0/24
  VpcCIDR: 10.0.0.0/16
  EnvironmentName: todo-app
  PrivateSubnet2CIDR: 10.0.4.0/24
  DynamoDBTableName: todos
  ContainerPort: '8089'
  PublicSubnet1CIDR: 10.0.1.0/24
tags: {}
